---
dist: trusty
language: python
python: "2.7"
before_install:
 - ln -s ansible-win-atomic-red-team ../juju4.win-atomic-red-team
install:
  - sudo apt-get install libxml2-utils
  - pip install ansible ansible-lint
  - ansible --version
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

script:
  - "echo \"[test-kitchen]\nlocalhost\" > inventory"

  - "ansible-lint tasks/main.yml"

# Check the role/playbook's syntax.
  - "ansible-playbook -i inventory --syntax-check test/integration/default/default.yml"
